"""Version information and lightweight constants for `deepagents-code`."""

import os

from deepagents_code._env_vars import (
    PYPI_INDEX_URL as _PYPI_INDEX_URL_ENV,
    PYPI_URL as _PYPI_URL_ENV,
    SDK_PYPI_URL as _SDK_PYPI_URL_ENV,
)

# Keep the `x-release-please-version` annotation — release-please uses it to
# bump `__version__` in sync with `pyproject.toml` on every release PR.
__version__ = "0.0.1"  # x-release-please-version

DISTRIBUTION_NAME = "zjcode"
"""Distribution (wheel/PyPI) name for this private-branded build.

Kept as a single constant so every place that would otherwise hard-code the
name (`uv tool install <name>`, `importlib.metadata.version(<name>)`, URL
paths on the private mirror, extras-preserving upgrade commands) can import
this one string. Changing the brand is a one-line edit here; keeping the
Python package directory `deepagents_code/` unchanged minimizes upstream
merge conflicts.
"""

BRAND_NAME = "zjcode"
"""Short user-visible command name shown in CLI help, splash, and errors.

Currently equal to `DISTRIBUTION_NAME` but kept separate: if you ever want
to ship a distribution named `zjcode-code` while users still type `zjcode`,
these two diverge. Only user-facing strings should read `BRAND_NAME` — never
`uv tool` commands or metadata lookups.
"""

DOCS_URL = "https://docs.langchain.com/oss/python/deepagents/code"
"""URL for `deepagents-code` documentation."""

PYPI_URL = os.environ.get(
    _PYPI_URL_ENV,
    f"http://8.152.204.58:40080/pypi/{DISTRIBUTION_NAME}/json",
)
"""PyPI JSON API endpoint for version checks.

Defaults to the private static mirror (port 40080), which serves a
Warehouse-compatible JSON document generated by `libs/code/run-build-upload.sh`
at publish time. The private `pypiserver` (port 48080) only exposes a Simple
Index, so the JSON API is hosted alongside the install page on the static site.
Override with `DEEPAGENTS_CODE_PYPI_URL` to point at public PyPI
(`https://pypi.org/pypi/deepagents-code/json`) or another mirror.
"""

PYPI_INDEX_URL = os.environ.get(
    _PYPI_INDEX_URL_ENV,
    "http://8.152.204.58:48080/simple/",
)
"""Simple Index URL used by `uv tool install -U` when upgrading dcode.

Defaults to the private `pypiserver` Simple Index (port 48080). Must stay in
sync with `PYPI_URL`: the JSON API answers "is there a new version?" and this
index answers "download it from where?". Override with
`DEEPAGENTS_CODE_PYPI_INDEX_URL` to point at public PyPI
(`https://pypi.org/simple`) or another mirror. The private mirror is expected
to resolve every runtime dependency as well — dcode does not fall back to
public PyPI, so a mirror that only serves `deepagents-code` will break
`/update` at dependency resolution.
"""

SDK_PYPI_URL = os.environ.get(
    _SDK_PYPI_URL_ENV,
    "http://8.152.204.58:40080/pypi/deepagents/json",
)
"""PyPI JSON API endpoint for reading `deepagents` SDK release metadata.

The CLI only reads release-age metadata from this endpoint; it never
performs SDK update checks. Defaults to the private static mirror; override
with `DEEPAGENTS_CODE_SDK_PYPI_URL` to use public PyPI
(`https://pypi.org/pypi/deepagents/json`).
"""

CHANGELOG_URL = (
    "https://github.com/langchain-ai/deepagents/blob/main/libs/code/CHANGELOG.md"
)
"""URL for the full changelog."""

USER_AGENT = f"{DISTRIBUTION_NAME}/{__version__} update-check"
"""User-Agent header sent with PyPI requests."""
