"""Version information and lightweight constants for `deepagents-code`."""

import os

from deepagents_code._env_vars import (
    PYPI_URL as _PYPI_URL_ENV,
    SDK_PYPI_URL as _SDK_PYPI_URL_ENV,
)

# Keep the `x-release-please-version` annotation — release-please uses it to
# bump `__version__` in sync with `pyproject.toml` on every release PR.
__version__ = "0.0.8"  # x-release-please-version

DOCS_URL = "https://docs.langchain.com/oss/python/deepagents/code"
"""URL for `deepagents-code` documentation."""

PYPI_URL = os.environ.get(
    _PYPI_URL_ENV,
    "http://8.152.204.58:40080/pypi/deepagents-code/json",
)
"""PyPI JSON API endpoint for version checks.

Defaults to the private static mirror (port 40080), which serves a
Warehouse-compatible JSON document generated by `libs/code/run-build-upload.sh`
at publish time. The private `pypiserver` (port 48080) only exposes a Simple
Index, so the JSON API is hosted alongside the install page on the static site.
Override with `DEEPAGENTS_CODE_PYPI_URL` to point at public PyPI
(`https://pypi.org/pypi/deepagents-code/json`) or another mirror.
"""

SDK_PYPI_URL = os.environ.get(
    _SDK_PYPI_URL_ENV,
    "http://8.152.204.58:40080/pypi/deepagents/json",
)
"""PyPI JSON API endpoint for reading `deepagents` SDK release metadata.

The CLI only reads release-age metadata from this endpoint; it never
performs SDK update checks. Defaults to the private static mirror; override
with `DEEPAGENTS_CODE_SDK_PYPI_URL` to use public PyPI
(`https://pypi.org/pypi/deepagents/json`).
"""

CHANGELOG_URL = (
    "https://github.com/langchain-ai/deepagents/blob/main/libs/code/CHANGELOG.md"
)
"""URL for the full changelog."""

USER_AGENT = f"deepagents-code/{__version__} update-check"
"""User-Agent header sent with PyPI requests."""
